---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "bookmydrdb"
  namespace: "default"
  labels:
    app: "bookmydrdb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "bookmydrdb"
  template:
    metadata:
      labels:
        app: "bookmydrdb"
    spec:
      containers:
      - name: "bookmydrdb-sha256-1"
        image: "gcr.io/charged-ground-326209/github.com/rukminiak041/bookmydrdb@sha256:f93eeff95db3f88e176643491159ae0596e5db6cfd1454da8e5781f59e926a96"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "bookmydrdb-hpa-9x0a"
  namespace: "default"
  labels:
    app: "bookmydrdb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "bookmydrdb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
